INSERT INTO ADMINISTRADOR VALUES ('123456789', 'Stuart', 'Jackson', 'Newman', 'jackson_st@gmail.com', 'stuart1234');

INSERT INTO TIEMPO_COMIDA VALUES (DEFAULT, 'Desayuno');
INSERT INTO TIEMPO_COMIDA VALUES (DEFAULT, 'Merienda Mañana');
INSERT INTO TIEMPO_COMIDA VALUES (DEFAULT, 'Almuerzo');
INSERT INTO TIEMPO_COMIDA VALUES (DEFAULT, 'Merienda Tarde');
INSERT INTO TIEMPO_COMIDA VALUES (DEFAULT, 'Cena');

INSERT INTO TIPO_COBRO VALUES (DEFAULT, 'Semanal');
INSERT INTO TIPO_COBRO VALUES (DEFAULT, 'Mensual');
INSERT INTO TIPO_COBRO VALUES (DEFAULT, 'Anual');