INSERT INTO ADMINISTRATOR VALUES ('123456789', 'Stuart', 'Jackson', 'Newman', 'jackson_st@gmail.com', '81dc9bdb52d04dc20036dbd8313ed055');

INSERT INTO MEAL_TIME VALUES (DEFAULT, 'Breakfast');
INSERT INTO MEAL_TIME VALUES (DEFAULT, 'Morning snack');
INSERT INTO MEAL_TIME VALUES (DEFAULT, 'Lunch');
INSERT INTO MEAL_TIME VALUES (DEFAULT, 'Afternoon snack');
INSERT INTO MEAL_TIME VALUES (DEFAULT, 'Dinner');

INSERT INTO PAYMENT_TYPE VALUES (DEFAULT, 'Weekly');
INSERT INTO PAYMENT_TYPE VALUES (DEFAULT, 'Monthly');
INSERT INTO PAYMENT_TYPE VALUES (DEFAULT, 'Anual');